name: ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    uses: reddoorla/.github/.github/workflows/ci.yml@ea80f72bc052ad0030a6af268a718dea260482ea # v1.1.0
    with:
      node-version: "24"
