name: ci
on:
  pull_request:
  push:
    branches: [main, staging]
jobs:
  ci:
    permissions:
      contents: read
      pull-requests: write
    uses: reddoorla/.github/.github/workflows/ci.yml@4a32c3d0caf2050d6f72274d3325f2306772860d # v1.3.0
    with:
      node-version: "24"
      netlify-site: "vineyard-custom-homes-staging"
